apiVersion: v1
kind: Namespace
metadata:
  name: et-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-nginx
  namespace: et-test
  labels:
    et-kind: et-update
spec:
  selector:
    matchLabels:
      et-kind: et-nginx
  template:
    metadata:
      labels:
        et-kind: et-nginx
    spec:
      containers:
      - name: et-nginx
        image: nginx
        envFrom:
        - configMapRef:
            name: et-cm
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: et-cm
  namespace: et-test
  labels:
    et-kind: et-watch
data:
  key: value
---
apiVersion: v1
kind: Secret
metadata:
  name: et-secret
  namespace: et-test
  labels:
    et-kind: et-watch
type: Opaque
data:
  key: dmFsdWUyMg==
---
apiVersion: trigger.eifa.org/v1
kind: EifaTrigger
metadata:
  name: et
  namespace: et-test
spec:
  watchList:
  - kind: ConfigMap
    labelSelector:
      et-kind: et-watch
  - kind: Secret
    labelSelector:
      et-kind: et-watch
  update:
    kind: Deployment
    labelSelector:
      et-kind: et-update
