apiVersion: v1
kind: Namespace
metadata:
  name: erfan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-nginx
  namespace: erfan
  labels:
    app: et-update
spec:
  selector:
    matchLabels:
      app: et-nginx
  template:
    metadata:
      labels:
        app: et-nginx
    spec:
      containers:
      - name: et-nginx
        image: repo-afra.snappfood.dev/nginx
        envFrom:
        - configMapRef:
            name: et-cm
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: et-cm
  namespace: erfan
  labels:
    app: et-watch
data:
  key: value22
---
apiVersion: v1
kind: Secret
metadata:
  name: et-secret
  namespace: erfan
  labels:
    app: et-watch
type: Opaque
data:
  key: dmFsdWUyMg==
---
apiVersion: trigger.eifa.org/v1
kind: EifaTrigger
metadata:
  name: et
  namespace: erfan
spec:
  watchList:
  - kind: ConfigMap
    labelSelector:
      app: et-watch
  - kind: Secret
    labelSelector:
      app: et-watch
  update:
    kind: Deployment
    labelSelector:
      app: et-update
