//go:build !ignore_autogenerated

/*
Copyright 2025 Erfan.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EifaTrigger) DeepCopyInto(out *EifaTrigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EifaTrigger.
func (in *EifaTrigger) DeepCopy() *EifaTrigger {
	if in == nil {
		return nil
	}
	out := new(EifaTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EifaTrigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EifaTriggerList) DeepCopyInto(out *EifaTriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EifaTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EifaTriggerList.
func (in *EifaTriggerList) DeepCopy() *EifaTriggerList {
	if in == nil {
		return nil
	}
	out := new(EifaTriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EifaTriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EifaTriggerSpec) DeepCopyInto(out *EifaTriggerSpec) {
	*out = *in
	in.Watch.DeepCopyInto(&out.Watch)
	in.Update.DeepCopyInto(&out.Update)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EifaTriggerSpec.
func (in *EifaTriggerSpec) DeepCopy() *EifaTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(EifaTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EifaTriggerStatus) DeepCopyInto(out *EifaTriggerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EifaTriggerStatus.
func (in *EifaTriggerStatus) DeepCopy() *EifaTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(EifaTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateSelector) DeepCopyInto(out *UpdateSelector) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSelector.
func (in *UpdateSelector) DeepCopy() *UpdateSelector {
	if in == nil {
		return nil
	}
	out := new(UpdateSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchSelector) DeepCopyInto(out *WatchSelector) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchSelector.
func (in *WatchSelector) DeepCopy() *WatchSelector {
	if in == nil {
		return nil
	}
	out := new(WatchSelector)
	in.DeepCopyInto(out)
	return out
}
