# permissions for end users to view eifatriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eifa-trigger-operator
    app.kubernetes.io/managed-by: kustomize
  name: eifatrigger-viewer-role
rules:
- apiGroups:
  - trigger.eifa.org
  resources:
  - eifatriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trigger.eifa.org
  resources:
  - eifatriggers/status
  verbs:
  - get
