---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trigger.eifa.org
  resources:
  - eifatriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trigger.eifa.org
  resources:
  - eifatriggers/finalizers
  verbs:
  - update
- apiGroups:
  - trigger.eifa.org
  resources:
  - eifatriggers/status
  verbs:
  - get
  - patch
  - update
